[profile.default]
src = 'contracts'
out = 'out'
# auto_detect_solc=true
solc_version='0.8.17'

[fmt]
line_length = 100
bracket_spacing = false
number_underscore = "thousands"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
