[profile.default]
src = 'src'
test = 'tests'
script = 'script'
out = 'out'
libs = ['lib']
solc_version = '0.8.19'
# auto_detect_solc=true

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = false
number_underscore = "thousands"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
