[profile.default]
src = 'contracts'
out = 'out'
remappings = [
  "OpenNFTs=."
]
auto_detect_solc=true
# solc_version='0.8.9'


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
