[profile.default]
src = 'contracts'
out = 'out'
# auto_detect_solc=true
solc_version='0.8.9'

[fmt]
number_underscore = "thousands"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
